function getMetricNumber(stats = {}, metricKey = "") {
  const rawValue = stats?.[metricKey]
  const numericValue = Number(rawValue)
  return Number.isFinite(numericValue) ? Math.max(0, numericValue) : null
}

export const ACHIEVEMENTS = [
  {
    id: "level-3",
    title: "Rookie Circuit",
    description: "Reach level 3.",
    iconKey: "level",
    metricKey: "level",
    targetValue: 3,
    computeCurrent: (stats) => getMetricNumber(stats, "level"),
  },
  {
    id: "level-5",
    title: "Arena Regular",
    description: "Reach level 5.",
    iconKey: "level",
    metricKey: "level",
    targetValue: 5,
    computeCurrent: (stats) => getMetricNumber(stats, "level"),
  },
  {
    id: "level-10",
    title: "Veteran Pulse",
    description: "Reach level 10.",
    iconKey: "level",
    metricKey: "level",
    targetValue: 10,
    computeCurrent: (stats) => getMetricNumber(stats, "level"),
  },
  {
    id: "rounds-1",
    title: "First Click",
    description: "Play 1 total round.",
    iconKey: "rounds",
    metricKey: "totalRounds",
    targetValue: 1,
    computeCurrent: (stats) => getMetricNumber(stats, "totalRounds"),
  },
  {
    id: "rounds-10",
    title: "Session Builder",
    description: "Play 10 total rounds.",
    iconKey: "rounds",
    metricKey: "totalRounds",
    targetValue: 10,
    computeCurrent: (stats) => getMetricNumber(stats, "totalRounds"),
  },
  {
    id: "rounds-50",
    title: "Endurance Grind",
    description: "Play 50 total rounds.",
    iconKey: "rounds",
    metricKey: "totalRounds",
    targetValue: 50,
    computeCurrent: (stats) => getMetricNumber(stats, "totalRounds"),
  },
  {
    id: "competitive-1",
    title: "Placement Ready",
    description: "Play 1 competitive round.",
    iconKey: "competitive",
    metricKey: "competitiveRounds",
    targetValue: 1,
    computeCurrent: (stats) => getMetricNumber(stats, "competitiveRounds"),
  },
  {
    id: "competitive-10",
    title: "Rank Ladder",
    description: "Play 10 competitive rounds.",
    iconKey: "competitive",
    metricKey: "competitiveRounds",
    targetValue: 10,
    computeCurrent: (stats) => getMetricNumber(stats, "competitiveRounds"),
  },
  {
    id: "competitive-50",
    title: "Rank Specialist",
    description: "Play 50 competitive rounds.",
    iconKey: "competitive",
    metricKey: "competitiveRounds",
    targetValue: 50,
    computeCurrent: (stats) => getMetricNumber(stats, "competitiveRounds"),
  },
  {
    id: "best-score-100",
    title: "Century Strike",
    description: "Reach a best score of 100.",
    iconKey: "score",
    metricKey: "bestScore",
    targetValue: 100,
    computeCurrent: (stats) => getMetricNumber(stats, "bestScore"),
  },
  {
    id: "best-score-200",
    title: "Double Century",
    description: "Reach a best score of 200.",
    iconKey: "score",
    metricKey: "bestScore",
    targetValue: 200,
    computeCurrent: (stats) => getMetricNumber(stats, "bestScore"),
  },
  {
    id: "best-score-300",
    title: "Triple Threat",
    description: "Reach a best score of 300.",
    iconKey: "score",
    metricKey: "bestScore",
    targetValue: 300,
    computeCurrent: (stats) => getMetricNumber(stats, "bestScore"),
  },
  {
    id: "best-streak-10",
    title: "Combo Apprentice",
    description: "Reach a best streak of 10.",
    iconKey: "streak",
    metricKey: "bestStreak",
    targetValue: 10,
    computeCurrent: (stats) => getMetricNumber(stats, "bestStreak"),
  },
  {
    id: "best-streak-25",
    title: "Combo Engineer",
    description: "Reach a best streak of 25.",
    iconKey: "streak",
    metricKey: "bestStreak",
    targetValue: 25,
    computeCurrent: (stats) => getMetricNumber(stats, "bestStreak"),
  },
  {
    id: "accuracy-80",
    title: "Steady Aim",
    description: "Reach 80% overall accuracy.",
    iconKey: "accuracy",
    metricKey: "overallAccuracyPercent",
    targetValue: 80,
    computeCurrent: (stats) => getMetricNumber(stats, "overallAccuracyPercent"),
  },
  {
    id: "accuracy-90",
    title: "Pinpoint Rhythm",
    description: "Reach 90% overall accuracy.",
    iconKey: "accuracy",
    metricKey: "overallAccuracyPercent",
    targetValue: 90,
    computeCurrent: (stats) => getMetricNumber(stats, "overallAccuracyPercent"),
  },
  {
    id: "clean-run-20",
    title: "Clean Run",
    description: "Finish a round with 20+ hits and zero misses.",
    iconKey: "clean",
    metricKey: "bestCleanRunHits",
    targetValue: 20,
    computeCurrent: (stats) => getMetricNumber(stats, "bestCleanRunHits"),
  },
  {
    id: "coins-500",
    title: "Coin Collector",
    description: "Earn 500 total coins.",
    iconKey: "economy",
    metricKey: "totalCoinsEarned",
    targetValue: 500,
    computeCurrent: (stats) => getMetricNumber(stats, "totalCoinsEarned"),
  },
]

